refactor: use cleaner imports
not sure if the imports with the .ts extension are causing problems but
on prod deployment I get this error on server startup:

```
server_1  | yarn run v1.22.4
server_1  | $ node -r tsconfig-paths/register src/index.js
server_1  | internal/modules/cjs/loader.js:979
server_1  |   throw err;
server_1  |   ^
server_1  |
server_1  | Error: Cannot find module '@port-of-mars/server/entity/Tournament.ts'
server_1  | Require stack:
server_1  | - /code/server/src/services/tournament.js
server_1  | - /code/server/src/services/auth.js
server_1  | - /code/server/src/services/index.js
server_1  | - /code/server/src/rooms/game/index.js
server_1  | - /code/server/src/index.js
server_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
server_1  |     at Function.Module._resolveFilename (/code/server/node_modules/tsconfig-paths/lib/register.js:75:40)
server_1  |     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
server_1  |     at Module.require (internal/modules/cjs/loader.js:1036:19)
server_1  |     at require (internal/modules/cjs/helpers.js:72:18)
server_1  |     at Object.<anonymous> (/code/server/src/services/tournament.js:20:25)
server_1  |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
server_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
server_1  |     at Module.load (internal/modules/cjs/loader.js:996:32)
server_1  |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
server_1  |     at Module.require (internal/modules/cjs/loader.js:1036:19)
server_1  |     at require (internal/modules/cjs/helpers.js:72:18)
server_1  |     at Object.<anonymous> (/code/server/src/services/auth.js:14:22)
server_1  |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
server_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
server_1  |     at Module.load (internal/modules/cjs/loader.js:996:32) {
server_1  |   code: 'MODULE_NOT_FOUND',
server_1  |   requireStack: [
server_1  |     '/code/server/src/services/tournament.js',
server_1  |     '/code/server/src/services/auth.js',
server_1  |     '/code/server/src/services/index.js',
server_1  |     '/code/server/src/rooms/game/index.js',
server_1  |     '/code/server/src/index.js'
server_1  |   ]
server_1  | }
server_1  | error Command failed with exit code 1.
server_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```